
# arduino [--verify|--upload] \
# 	[--board package:arch:board[:parameters]] \
# 	[--port portname] \
# 	[--pref name=value] \
# 	[-v|--verbose] \
# 	[--preserve-temp-files] \
# 	[FILE.ino]

.PHONY: verify upload

	BOARD=


verify:
	arduino --verify mkr1000-color-serve.ino

upload:


